services:
  app:
    build: .
    env_file: .env
    network_mode: host
    restart: unless-stopped
    environment:
      DB_HOST: localhost

  migrate:
    build:
      context: .
      target: builder
    env_file: .env
    network_mode: host
    environment:
      DB_HOST: localhost
    command: npm run migration:run
    profiles:
      - migrate
